server:
  port: 8102
spring:
    datasource:
       datasource-name: default
       driver-class-name: com.mysql.jdbc.Driver
       username: root
       password: root
       url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/easy_jdbc?useUnicode=true&useSSL=false&characterEncoding=UTF-8
easyjdbc:
  dialect: mysql
  basePackage:  com.xphsc.easyjdbc.dao
logging:
  level:
    com.xphsc: debug
